/**
 * Application index file – the app execution starts here
 *
 * auto-generated by create-react-app script
 */
// react
import React, { Suspense } from 'react';
import ReactDOM from 'react-dom';

import { Provider } from 'react-redux';
import store from './store';

// for bundling
import './i18n';

// our stuff
import Loading from './components/Loading';
import App from './App';

ReactDOM.render(
    <Suspense fallback={<Loading />}>
        <Provider store={store}>
            <App />
        </Provider>
    </Suspense>,
    document.getElementById('container')
);
