/**
 * Application index file – the app execution starts here
 *
 * Auto-generated by create-react-app script
 */
import React from 'react';
import ReactDOM from 'react-dom';

import App from './App.js';

ReactDOM.render(<App />, document.getElementById('container'));
